### ISSUE TITLE
Tests do not wait for the main build before starting

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/opam-repo-ci#39]
I can't find how it's possible in the code but in the logs I'm seeing the tests starting almost at the same time as the main builds.
For instance:
* https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/fe90854c10eaa614622f7f8585c8e38c62a4e644/variant/compilers,4.08,odate.0.6
* https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/fe90854c10eaa614622f7f8585c8e38c62a4e644/variant/compilers,4.08,odate.0.6,tests

**Comment by talex5** [comment]
You merged a commit to opam-repository at 2020-11-18 16:24:11, which is just before these jobs started, so this was probably a rebuild.

The tests probably ran immediately because the output of the build was latched.

I admit I hadn't thought about it doing that, but it's not necessarily a bad thing! It means that if the build was passing before then we assume it's worth rebuilding the tests immediately.

**Comment by kit-ty-kate** [comment]
The main thing is that it's a big waste of resource in ocluster. The main build and all it dependencies are built twice at the same time on the same machine(!) whereas if it waited for the main build it would only build it once then build the tests.

**Comment by talex5** [comment]
If they're building the same thing on the same machine then it will just do one build and stream the same logs to both clients (for that build step).

**Comment by shonfeder** [comment]
It doesn't sound like this is actually an issue, from the discussion. Please correct me and re-open if I am mistaken!
